jobs:
  check_time:
    runs-on: ubuntu-latest
    steps:
      - name: 输出当前时间（UTC 和 CST）
        run: |
          echo "当前 UTC 时间: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          echo "当前 CST 时间: $(TZ='Asia/Shanghai' date +"%Y-%m-%d %H:%M:%S CST")"
